version: '3'
services:
  cli:
    build:
      context: cli
      args:
        PHP_OTHER_EXT:
        PHP_CORE_EXT:
        PHP_INSTALL_GD:
    volumes:
      - ${APPLICATION}:/www
    networks:
      - frontend
      - backend
  php:
    build:
      context: php
      args:
        PHP_OTHER_EXT:
        PHP_CORE_EXT:
        PHP_INSTALL_GD:
    volumes:
      - ${APPLICATION}:/www
#      - ../:/www
#      - ./conf:/usr/local/etc/php
#      - ./logs:/phplogs
    networks:
      - frontend
      - backend
  nginx:
    build: nginx
    ports:
      - "8012:80"
    volumes:
      - ${APPLICATION}:/www
    networks:
      - frontend
      - backend
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"


