version: '3'
services:
  cli:
    image: "ccq18/php-cli:7.1"
    volumes:
      - ${APPLICATION}:/www
    networks:
      - frontend
  fpm:
    image: "ccq18/php-fpm:7.1"
    volumes:
      - ${APPLICATION}:/www
    networks:
      - frontend
  nginx:
    image: "ccq18/nginx"
    ports:
      - "${PORT}:8001"
    volumes:
      - ${APPLICATION}:/www
      - ${APPLICATION}/storage/logs:/log/nginx
    networks:
      - frontend
#  cron:
#    build: cron
#    volumes:
#      - ${APPLICATION}:/www
#      - ${APPLICATION}/storage/logs:/var/log
#    networks:
#      - frontend
#  supervisor:
#    build: supervisor
#    volumes:
#      - ${APPLICATION}:/www
#      - ${APPLICATION}/storage/logs:/var/log
#    networks:
#      - frontend

networks:
  frontend:
    driver: "bridge"
#  backend:
#    driver: "bridge"


